### ISSUE TITLE
found 2 falses (the FIRST two players who joined got flagged)

### ISSUE THREAD

**Issue by GreenedDev** [growtoups/ASN_LIST#10]
as12874 - k2enny
as24560 -k2enny indian friend

**Comment by growtoups** [comment]
Fixed.

**Comment by GreenedDev** [comment]
where did you even get this list from?

**Comment by growtoups** [comment]
ipinfo.io/hosting basically however the hosting category contains at the same time residential isps since alot of them offers hosting too
