### ISSUE TITLE
Blocking safe ASNs

### ISSUE THREAD

**Issue by sefinek24** [growtoups/ASN_LIST#8]
I do not recommend using this, as server queries from regular users were already being blocked just a few minutes after this list was implemented in Cloudflare.

The list also includes ASNs such as `ORACLE-BMC`, `GOOGLE-CLOUD-PLATFORM`, `Shields.io`, `Better Uptime Bot`,  etc which are considered safe. Blocking them makes no sense.

This list is much better: https://github.com/sefinek24/cloudflare-waf-expressions

**Comment by sefinek24** [comment]
Thank you for the explanation.

In my opinion, completely blocking internet service providers is not the right solution and should not be applied, especially considering that most DDoS attacks are carried out using VPNs or proxy servers. Completely blocking an ASN from which a DDoS attack originated can deprive innocent users, who are using the same proxy or VPN, of access to the website.

Cloudflare already offers an Anti-DDoS service, eliminating the need for further enhancements. Efforts could instead be concentrated on blocking bot traffic, particularly targeting CMS platforms like WordPress. Traffic from such bots should be blocked when WordPress is not in use.

**Comment by growtoups** [comment]
Understood. While Cloudflare's anti-DDoS measures are effective, they are not foolproof and can sometimes let threats slip through. By targeting hosting ASNs specifically for blocking, it becomes "almost" impossible for a DDoS attack to succeed. As mentioned earlier, this approach does not account for residential DDoS attacks, as it focuses on the more easily identifiable hosting-based threats. Exceptions can be effortlessly incorporated by adding exclusion rules in the WAF or simply by removing specific ASNs from the block list.

**Comment by sefinek24** [comment]
Bro, no sane person would conduct an attack through Cloudflare. There are several ways to obtain the real IP address of a machine.

Blocking ASN in CF is futile and will only lead to a loss of users. I host my website on my own server set up at home, using the Cloudflared tunnel, and I have never encountered any DDoS attacks (considering only the logs from the original server, which does not have EVEN ONE PORT open).

In the CF logs, I only have over +2k blocked requests (everyday) from bots (I configured the WAF myself).

![](https://cdn.sefinek.net/static/01.02.2024/brave_lCAgup7icec3.png)
![](https://cdn.sefinek.net/static/01.02.2024/brave_t0HBSvoLECKu.png)

**Comment by growtoups** [comment]
To be candid, I have experienced multiple DDoS attacks that penetrated Cloudflare's defenses, which Cloudflare alone was unable to mitigate effectively.

**Comment by sefinek24** [comment]
PS: no one will specially and magically become an internet service provider to conduct pathetic DDoS attacks on a proxy like Cloudflare to cause downtime for a given website.
As I said, DDoS attacks usually come from proxy servers, VPNs, VPS. They can even originate from the attacker's original ISP if it fails to protect itself. Why should other people using the same ISP as the attacker lose access to a specific site?

**Comment by sefinek24** [comment]
can you send a screenshot of an example attack?

**Comment by growtoups** [comment]
Well, not anymore, as these incidents occurred on past domains that I no longer own.

**Comment by sefinek24** [comment]
At least describe what exactly was happening, because I'm quite curious. I assume that one of your friends was messing around and launched a bot that kept refreshing your page constantly.

**Comment by growtoups** [comment]
> PS: no one will specially and magically become an internet service provider to conduct pathetic DDoS attacks on a proxy like Cloudflare to cause downtime for a given website. As I said, DDoS attacks usually come from proxy servers, VPNs, VPS. They can even originate from the attacker's original ISP if it fails to protect itself. Why should other people using the same ISP as the attacker lose access to a specific site?


As I've previously mentioned, the main goal of the ASN list is to block datacenter ASNs, not residential ones. Indeed, many residential ISP ASNs have inadvertently been included due to insufficient scrutiny in my initial review process.

**Comment by sefinek24** [comment]
Alright
